python pc_sim.py --object flat_screwdriver --num_sim 150 --folder_path grasp_soap
python pc_sim.py --object potato_chip_1 --num_sim 150 --folder_path grasp_soap
python pc_sim.py --object two_color_hammer --num_sim 150 --folder_path grasp_soap
python pc_sim.py --object suger_1 --num_sim 150 --folder_path grasp_soap
python pc_sim.py --object pudding_box --num_sim 150 --folder_path grasp_soap
python pc_sim.py --object toothpaste_1 --num_sim 150 --folder_path grasp_soap
python pc_sim.py --object plate --num_sim 150 --folder_path grasp_soap
python pc_sim.py --object potato_chip_3 --num_sim 150 --folder_path grasp_soap
python pc_sim.py --object soap --num_sim 150 --folder_path grasp_soap
python pc_sim.py --object green_bowl --num_sim 150 --folder_path grasp_soap
python pc_sim.py --object plastic_strawberry --num_sim 150 --folder_path grasp_soap
python pc_sim.py --object lipton_tea --num_sim 150 --folder_path grasp_soap
python pc_sim.py --object round_plate_4 --num_sim 150 --folder_path grasp_soap
python pc_sim.py --object blue_cup --num_sim 150 --folder_path grasp_soap
python pc_sim.py --object correction_fluid --num_sim 150 --folder_path grasp_soap
python pc_sim.py --object plastic_pear --num_sim 150 --folder_path grasp_soap
python pc_sim.py --object square_plate_2 --num_sim 150 --folder_path grasp_soap
python pc_sim.py --object gelatin_box --num_sim 150 --folder_path grasp_soap
python pc_sim.py --object mug --num_sim 150 --folder_path grasp_soap
python pc_sim.py --object red_marker --num_sim 150 --folder_path grasp_soap
python pc_sim.py --object plate_holder --num_sim 150 --folder_path grasp_soap
python pc_sim.py --object round_plate_1 --num_sim 150 --folder_path grasp_soap
python pc_sim.py --object doraemon_plate --num_sim 150 --folder_path grasp_soap
python pc_sim.py --object shampoo --num_sim 150 --folder_path grasp_soap
python pc_sim.py --object plastic_plum --num_sim 150 --folder_path grasp_soap
python pc_sim.py --object orion_pie --num_sim 150 --folder_path grasp_soap
python pc_sim.py --object fork --num_sim 150 --folder_path grasp_soap
python pc_sim.py --object magic_clean --num_sim 150 --folder_path grasp_soap
python pc_sim.py --object square_plate_4 --num_sim 150 --folder_path grasp_soap
python pc_sim.py --object spoon --num_sim 150 --folder_path grasp_soap
python pc_sim.py --object potato_chip_2 --num_sim 150 --folder_path grasp_soap
python pc_sim.py --object book_4 --num_sim 150 --folder_path grasp_soap
python pc_sim.py --object blue_tea_box --num_sim 150 --folder_path grasp_soap
python pc_sim.py --object green_cup --num_sim 150 --folder_path grasp_soap
python pc_sim.py --object poker_1 --num_sim 150 --folder_path grasp_soap
python pc_sim.py --object book_5 --num_sim 150 --folder_path grasp_soap
python pc_sim.py --object book_6 --num_sim 150 --folder_path grasp_soap
python pc_sim.py --object phillips_screwdriver --num_sim 150 --folder_path grasp_soap
python pc_sim.py --object plastic_apple --num_sim 150 --folder_path grasp_soap
python pc_sim.py --object square_plate_3 --num_sim 150 --folder_path grasp_soap
python pc_sim.py --object blue_moon --num_sim 150 --folder_path grasp_soap
python pc_sim.py --object clear_box_1 --num_sim 150 --folder_path grasp_soap
python pc_sim.py --object suger_3 --num_sim 150 --folder_path grasp_soap
python pc_sim.py --object bowl --num_sim 150 --folder_path grasp_soap
python pc_sim.py --object book_1 --num_sim 150 --folder_path grasp_soap
python pc_sim.py --object large_clamp --num_sim 150 --folder_path grasp_soap
python pc_sim.py --object yellow_bowl --num_sim 150 --folder_path grasp_soap
python pc_sim.py --object orange_cup --num_sim 150 --folder_path grasp_soap
python pc_sim.py --object bleach_cleanser --num_sim 150 --folder_path grasp_soap
python pc_sim.py --object square_plate_1 --num_sim 150 --folder_path grasp_soap
python pc_sim.py --object pink_tea_box --num_sim 150 --folder_path grasp_soap
python pc_sim.py --object repellent --num_sim 150 --folder_path grasp_soap
python pc_sim.py --object plastic_lemon --num_sim 150 --folder_path grasp_soap
python pc_sim.py --object pen_container_1 --num_sim 150 --folder_path grasp_soap
python pc_sim.py --object book_holder_1 --num_sim 150 --folder_path grasp_soap
python pc_sim.py --object remote_controller_1 --num_sim 150 --folder_path grasp_soap
python pc_sim.py --object mini_claw_hammer_1 --num_sim 150 --folder_path grasp_soap
python pc_sim.py --object scissors --num_sim 150 --folder_path grasp_soap
python pc_sim.py --object cleanser --num_sim 150 --folder_path grasp_soap
python pc_sim.py --object round_plate_3 --num_sim 150 --folder_path grasp_soap
python pc_sim.py --object book_holder_2 --num_sim 150 --folder_path grasp_soap
python pc_sim.py --object power_drill --num_sim 150 --folder_path grasp_soap
python pc_sim.py --object suger_2 --num_sim 150 --folder_path grasp_soap
python pc_sim.py --object medium_clamp --num_sim 150 --folder_path grasp_soap
python pc_sim.py --object small_clamp --num_sim 150 --folder_path grasp_soap
python pc_sim.py --object extra_large_clamp --num_sim 150 --folder_path grasp_soap
python pc_sim.py --object stapler_2 --num_sim 150 --folder_path grasp_soap
python pc_sim.py --object remote_controller_2 --num_sim 150 --folder_path grasp_soap
python pc_sim.py --object glue_1 --num_sim 150 --folder_path grasp_soap
python pc_sim.py --object plastic_banana --num_sim 150 --folder_path grasp_soap
python pc_sim.py --object plastic_orange --num_sim 150 --folder_path grasp_soap
python pc_sim.py --object large_marker --num_sim 150 --folder_path grasp_soap
python pc_sim.py --object knife --num_sim 150 --folder_path grasp_soap
python pc_sim.py --object pitcher --num_sim 150 --folder_path grasp_soap
python pc_sim.py --object blue_plate --num_sim 150 --folder_path grasp_soap
python pc_sim.py --object conditioner --num_sim 150 --folder_path grasp_soap
python pc_sim.py --object cracker_box --num_sim 150 --folder_path grasp_soap
python pc_sim.py --object doraemon_bowl --num_sim 150 --folder_path grasp_soap
python pc_sim.py --object stapler_1 --num_sim 150 --folder_path grasp_soap
python pc_sim.py --object black_marker --num_sim 150 --folder_path grasp_soap
python pc_sim.py --object grey_plate --num_sim 150 --folder_path grasp_soap
python pc_sim.py --object sugar_box --num_sim 150 --folder_path grasp_soap
python pc_sim.py --object blue_marker --num_sim 150 --folder_path grasp_soap
python pc_sim.py --object book_holder_3 --num_sim 150 --folder_path grasp_soap
python pc_sim.py --object round_plate_2 --num_sim 150 --folder_path grasp_soap
python pc_sim.py --object yellow_cup --num_sim 150 --folder_path grasp_soap
python pc_sim.py --object soap_dish --num_sim 150 --folder_path grasp_soap
python pc_sim.py --object small_marker --num_sim 150 --folder_path grasp_soap
python pc_sim.py --object book_3 --num_sim 150 --folder_path grasp_soap
python pc_sim.py --object clear_box_2 --num_sim 150 --folder_path grasp_soap
python pc_sim.py --object glue_2 --num_sim 150 --folder_path grasp_soap
python pc_sim.py --object plastic_peach --num_sim 150 --folder_path grasp_soap
python pc_sim.py --object clear_box --num_sim 150 --folder_path grasp_soap
python pc_sim.py --object book_2 --num_sim 150 --folder_path grasp_soap